export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body>
                <header>
                    {/* <h2>Header Auth</h2> */}
                </header>

                <main>
                    {children}
                </main>

                <footer>
                    {/* <h2>Footer Auth</h2> */}
                </footer>

            </body>
        </html>
    );
}
