import { DashboardResourcesProvider } from './context/DashboardResourcesProvider'

export const metadata = {
  title: 'Ronda',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return <DashboardResourcesProvider>{children}</DashboardResourcesProvider>
}
