import { ToastContainer } from 'react-toastify';

import Footer from './components/FooterComponet/Footer';
import NavView from './components/NavView/NavView';
import UserStatus from './components/UserStatus/UserStatus';

export const metadata = {
    title: "Ronda",
    description: "Generated by create next app",
}

export default function layout({ children }) {
    return (
        <body>
            <header>
                <NavView />
            </header>

            <>{children}</>

            <Footer />
            <ToastContainer />
            <UserStatus />
        </body>
    );
}
