import { ToastContainer } from "react-toastify"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function layout({ children }) {
    return (
        <body>
            {children}
            <ToastContainer />
        </body>
    )
}
