import '../globals.css'
import { MainButtons } from './dashboard/components'
import styles from './dashboard/components/MainButtons/styles/MainButtons.module.css'

export const metadata = {
  title: 'Ronda',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <main className={styles.container}>
          <MainButtons />
          <>{children}</>
        </main>
      </body>
    </html>
  )
}
