import "./globals.css";
import Footer from "../components/FooterComponet/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header> este es el header</header>
        <>{children}</>
      <Footer></Footer>
      </body>
    </html>
  );
}
