import { Inter } from "next/font/google";
import "./globals.css";
import { NavView } from '@/components';
import Footer from "@/components/FooterComponet/Footer";
const inter = Inter({ subsets: ["latin"] });
import LoginForm from "@/components/loginform/LoginForm";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        {/* <NavView />
        <>{children}</>
        <Footer></Footer> */}
        <LoginForm/>
      </body>
    </html>
  );
}