import './globals.css';
import { NavView, Footer } from '@/components';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <NavView />
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
