import { ToastContainer } from 'react-toastify'


import Navbar from '../(main)/components/navbar/Navbar'

export const metadata = {
  title: 'Ronda',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <body>
      <Navbar />
      {children}
      <ToastContainer />
    </body>
  )
}
