import { NavView } from '../(main)/components'

export const metadata = {
  title: 'Ronda',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <body>
      <NavView />
      {children}
    </body>
  )
}
